//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rp3.AgendaComercial.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageValidation() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rp3.AgendaComercial.Resources.ErrorMessageValidation", typeof(ErrorMessageValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el Cliente o Contacto para la Visita.
        /// </summary>
        public static string AgendaClienteOContactoRequerido {
            get {
                return ResourceManager.GetString("AgendaClienteOContactoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija la Dirección de la Visita.
        /// </summary>
        public static string AgendaDireccionRequerida {
            get {
                return ResourceManager.GetString("AgendaDireccionRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede Programar una Visita de una Fecha Pasada.
        /// </summary>
        public static string AgendaFechaPasada {
            get {
                return ResourceManager.GetString("AgendaFechaPasada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede actualizar una visita en con el estado actual: {0}.
        /// </summary>
        public static string AgendaModificarEstadoNoValido {
            get {
                return ResourceManager.GetString("AgendaModificarEstadoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un Motivo de Reprogramación.
        /// </summary>
        public static string AgendaMotivoReprogramacion {
            get {
                return ResourceManager.GetString("AgendaMotivoReprogramacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente ya existe.
        /// </summary>
        public static string AgenteRutaRepetido {
            get {
                return ResourceManager.GetString("AgenteRutaRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario seleccionado ya existe como Agente.
        /// </summary>
        public static string AgenteUsuarioRepetido {
            get {
                return ResourceManager.GetString("AgenteUsuarioRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información incompleta.
        /// </summary>
        public static string DatosIncompletos {
            get {
                return ResourceManager.GetString("DatosIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de inicio no puede ser mayor a la fecha de fin.
        /// </summary>
        public static string FechaInicioMayorFechaFin {
            get {
                return ResourceManager.GetString("FechaInicioMayorFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Hora de Inicio no debe ser mayor a la Hora Final.
        /// </summary>
        public static string HoraInicioMayorHoraFin {
            get {
                return ResourceManager.GetString("HoraInicioMayorHoraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingreser la fecha Hasta.
        /// </summary>
        public static string IngresarFechaHasta {
            get {
                return ResourceManager.GetString("IngresarFechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de inicio no puede ser mayor a la de fin.
        /// </summary>
        public static string InicioMayorFin {
            get {
                return ResourceManager.GetString("InicioMayorFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud de {0} debe estar comprendida entre {2} y {1}.
        /// </summary>
        public static string MaxMinStringLength {
            get {
                return ResourceManager.GetString("MaxMinStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar la observación.
        /// </summary>
        public static string ObservacionObligatoria {
            get {
                return ResourceManager.GetString("ObservacionObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar la observación del Supervisor.
        /// </summary>
        public static string ObservacionSupervisorObligatoria {
            get {
                return ResourceManager.GetString("ObservacionSupervisorObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el Agente o el Grupo para el Permiso.
        /// </summary>
        public static string PermisoAgenteOGrupoRequerido {
            get {
                return ResourceManager.GetString("PermisoAgenteOGrupoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible agregar un permiso previo a una fecha menor a la actual.
        /// </summary>
        public static string PermisoPrevioFechaMenorFechaActual {
            get {
                return ResourceManager.GetString("PermisoPrevioFechaMenorFechaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo {0} es requerido.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe de ingresar días de la semana.
        /// </summary>
        public static string SinDias {
            get {
                return ResourceManager.GetString("SinDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe de ingresar una fecha de fin.
        /// </summary>
        public static string SinFechaFin {
            get {
                return ResourceManager.GetString("SinFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe de ingresar una fecha de inicio.
        /// </summary>
        public static string SinFechaInicio {
            get {
                return ResourceManager.GetString("SinFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe agregar elementos a la zona.
        /// </summary>
        public static string ZonaSinElementos {
            get {
                return ResourceManager.GetString("ZonaSinElementos", resourceCulture);
            }
        }
    }
}
