//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rp3.AgendaComercial.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelFor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelFor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rp3.AgendaComercial.Resources.LabelFor", typeof(LabelFor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad.
        /// </summary>
        public static string Actividad {
            get {
                return ResourceManager.GetString("Actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Económica.
        /// </summary>
        public static string ActividadEconomica {
            get {
                return ResourceManager.GetString("ActividadEconomica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar los datos de los clientes en cada visita.
        /// </summary>
        public static string ActualizarClienteEnCadaVisita {
            get {
                return ResourceManager.GetString("ActualizarClienteEnCadaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar los datos de los clientes en la visita, solo si no están completos.
        /// </summary>
        public static string ActualizarClienteEnVisitaSoloSiFaltanDatos {
            get {
                return ResourceManager.GetString("ActualizarClienteEnVisitaSoloSiFaltanDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        public static string Agente {
            get {
                return ResourceManager.GetString("Agente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente o Grupo.
        /// </summary>
        public static string AgenteGrupo {
            get {
                return ResourceManager.GetString("AgenteGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente Últ. Visita.
        /// </summary>
        public static string AgenteUltimaVisita {
            get {
                return ResourceManager.GetString("AgenteUltimaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Zona.
        /// </summary>
        public static string AgregarAZona {
            get {
                return ResourceManager.GetString("AgregarAZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+) Permiso.
        /// </summary>
        public static string AgregarPermiso {
            get {
                return ResourceManager.GetString("AgregarPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+) Visita.
        /// </summary>
        public static string AgregarVisita {
            get {
                return ResourceManager.GetString("AgregarVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anular.
        /// </summary>
        public static string Anular {
            get {
                return ResourceManager.GetString("Anular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Apellido1 {
            get {
                return ResourceManager.GetString("Apellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Apellido.
        /// </summary>
        public static string Apellido2 {
            get {
                return ResourceManager.GetString("Apellido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica Ubicación en Break.
        /// </summary>
        public static string AplicaBreak {
            get {
                return ResourceManager.GetString("AplicaBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica Marcación.
        /// </summary>
        public static string AplicaMarcacion {
            get {
                return ResourceManager.GetString("AplicaMarcacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AplicarTodas.
        /// </summary>
        public static string AplicarTodas {
            get {
                return ResourceManager.GetString("AplicarTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica Ruta.
        /// </summary>
        public static string AplicaRuta {
            get {
                return ResourceManager.GetString("AplicaRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica Todas las Rutas.
        /// </summary>
        public static string AplicaTodasLasRutas {
            get {
                return ResourceManager.GetString("AplicaTodasLasRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        public static string Aprobar {
            get {
                return ResourceManager.GetString("Aprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencias.
        /// </summary>
        public static string Asistencias {
            get {
                return ResourceManager.GetString("Asistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistentes.
        /// </summary>
        public static string Asistentes {
            get {
                return ResourceManager.GetString("Asistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string Asunto {
            get {
                return ResourceManager.GetString("Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrasos.
        /// </summary>
        public static string Atrasos {
            get {
                return ResourceManager.GetString("Atrasos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrasos (min.).
        /// </summary>
        public static string AtrasosMinutos {
            get {
                return ResourceManager.GetString("AtrasosMinutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausencias.
        /// </summary>
        public static string Ausencias {
            get {
                return ResourceManager.GetString("Ausencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausente.
        /// </summary>
        public static string Ausente {
            get {
                return ResourceManager.GetString("Ausente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automática.
        /// </summary>
        public static string Automatica {
            get {
                return ResourceManager.GetString("Automatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por: Cliente, Dirección, Cargo e Identificación.
        /// </summary>
        public static string BuscarEnAgenda {
            get {
                return ResourceManager.GetString("BuscarEnAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por: Cliente, Agente, Dirección, Cargo e Identificación.
        /// </summary>
        public static string BuscarEnAgendaAgente {
            get {
                return ResourceManager.GetString("BuscarEnAgendaAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por: Nombre, Dirección, Etapa y Agente.
        /// </summary>
        public static string BuscarOportunidades {
            get {
                return ResourceManager.GetString("BuscarOportunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        public static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        public static string Calendario {
            get {
                return ResourceManager.GetString("Calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación.
        /// </summary>
        public static string Calificacion {
            get {
                return ResourceManager.GetString("Calificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo.
        /// </summary>
        public static string Campo {
            get {
                return ResourceManager.GetString("Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal.
        /// </summary>
        public static string Canal {
            get {
                return ResourceManager.GetString("Canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canales.
        /// </summary>
        public static string Canales {
            get {
                return ResourceManager.GetString("Canales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturar.
        /// </summary>
        public static string Capturar {
            get {
                return ResourceManager.GetString("Capturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad / Población.
        /// </summary>
        public static string CiudadPoblacion {
            get {
                return ResourceManager.GetString("CiudadPoblacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes sin Ruta.
        /// </summary>
        public static string ClientesSinRuta {
            get {
                return ResourceManager.GetString("ClientesSinRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Externo.
        /// </summary>
        public static string CodigoExterno {
            get {
                return ResourceManager.GetString("CodigoExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string Consultar {
            get {
                return ResourceManager.GetString("Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string ConsultarUbicacionAgentes {
            get {
                return ResourceManager.GetString("ConsultarUbicacionAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string CorreoElectronico {
            get {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Visita.
        /// </summary>
        public static string CrearAgenda {
            get {
                return ResourceManager.GetString("CrearAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Categoría.
        /// </summary>
        public static string CrearCategoria {
            get {
                return ResourceManager.GetString("CrearCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Opciones.
        /// </summary>
        public static string CrearOpciones {
            get {
                return ResourceManager.GetString("CrearOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Permiso.
        /// </summary>
        public static string CrearPermiso {
            get {
                return ResourceManager.GetString("CrearPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Más.
        /// </summary>
        public static string DashboardVerMas {
            get {
                return ResourceManager.GetString("DashboardVerMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos que se podrán editar.
        /// </summary>
        public static string DatosEditar {
            get {
                return ResourceManager.GetString("DatosEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        public static string Descuento {
            get {
                return ResourceManager.GetString("Descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatarios.
        /// </summary>
        public static string Destinatarios {
            get {
                return ResourceManager.GetString("Destinatarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Detalle {
            get {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detenido.
        /// </summary>
        public static string Detenido {
            get {
                return ResourceManager.GetString("Detenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        public static string Dia {
            get {
                return ResourceManager.GetString("Dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to día(s).
        /// </summary>
        public static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Inactividad.
        /// </summary>
        public static string DiasInactividad {
            get {
                return ResourceManager.GetString("DiasInactividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Transcurridos.
        /// </summary>
        public static string DiasTranscurridos {
            get {
                return ResourceManager.GetString("DiasTranscurridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        public static string Duracion {
            get {
                return ResourceManager.GetString("Duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días.
        /// </summary>
        public static string DuracionDias {
            get {
                return ResourceManager.GetString("DuracionDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Visita.
        /// </summary>
        public static string EditarAgenda {
            get {
                return ResourceManager.GetString("EditarAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectividad.
        /// </summary>
        public static string Efectividad {
            get {
                return ResourceManager.GetString("Efectividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Eficiencia.
        /// </summary>
        public static string EficienciaPorcentaje {
            get {
                return ResourceManager.GetString("EficienciaPorcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El.
        /// </summary>
        public static string El {
            get {
                return ResourceManager.GetString("El", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Movimiento.
        /// </summary>
        public static string EnMovimiento {
            get {
                return ResourceManager.GetString("EnMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Abierta.
        /// </summary>
        public static string EsAbierta {
            get {
                return ResourceManager.GetString("EsAbierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Administrador.
        /// </summary>
        public static string EsAdministrador {
            get {
                return ResourceManager.GetString("EsAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del Agente.
        /// </summary>
        public static string EscribaAgente {
            get {
                return ResourceManager.GetString("EscribaAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Predeterminado.
        /// </summary>
        public static string EsDefault {
            get {
                return ResourceManager.GetString("EsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Día Parcial.
        /// </summary>
        public static string EsDiaParcial {
            get {
                return ResourceManager.GetString("EsDiaParcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Indefinida.
        /// </summary>
        public static string EsIndefinida {
            get {
                return ResourceManager.GetString("EsIndefinida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene 2 Jornadas?.
        /// </summary>
        public static string EsJornada2 {
            get {
                return ResourceManager.GetString("EsJornada2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboral.
        /// </summary>
        public static string EsLaboral {
            get {
                return ResourceManager.GetString("EsLaboral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string EsPrincipal {
            get {
                return ResourceManager.GetString("EsPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Supervisor.
        /// </summary>
        public static string EsSupervisor {
            get {
                return ResourceManager.GetString("EsSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer.
        /// </summary>
        public static string Establecer {
            get {
                return ResourceManager.GetString("Establecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadísticas.
        /// </summary>
        public static string Estadisticas {
            get {
                return ResourceManager.GetString("Estadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EstadoAgenda {
            get {
                return ResourceManager.GetString("EstadoAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Visitado.
        /// </summary>
        public static string EstadoAgendaNoRealizado {
            get {
                return ResourceManager.GetString("EstadoAgendaNoRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        public static string EstadoAgendaPendiente {
            get {
                return ResourceManager.GetString("EstadoAgendaPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitado.
        /// </summary>
        public static string EstadoAgendaRealizado {
            get {
                return ResourceManager.GetString("EstadoAgendaRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprogramado.
        /// </summary>
        public static string EstadoAgendaReprogramado {
            get {
                return ResourceManager.GetString("EstadoAgendaReprogramado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil.
        /// </summary>
        public static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica en cualquier año.
        /// </summary>
        public static string EsteAnio {
            get {
                return ResourceManager.GetString("EsteAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los días de esta etapa se definiran al crear la oportunidad?.
        /// </summary>
        public static string EsVariable {
            get {
                return ResourceManager.GetString("EsVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Etapa {
            get {
                return ResourceManager.GetString("Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Cliente(s).
        /// </summary>
        public static string ExcluirCliente {
            get {
                return ResourceManager.GetString("ExcluirCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una tarea de este tipo asignada a una o más rutas, por ende no se permite asignar a todas las Rutas.
        /// </summary>
        public static string ExisteTareaTipoTodasRutas {
            get {
                return ResourceManager.GetString("ExisteTareaTipoTodasRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string FechaFin {
            get {
                return ResourceManager.GetString("FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin Gestión.
        /// </summary>
        public static string FechaFinGestion {
            get {
                return ResourceManager.GetString("FechaFinGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Gestión.
        /// </summary>
        public static string FechaGestion {
            get {
                return ResourceManager.GetString("FechaGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio Gestión.
        /// </summary>
        public static string FechaInicioGestion {
            get {
                return ResourceManager.GetString("FechaInicioGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Ult. Modificación.
        /// </summary>
        public static string FechaUltimaModificacion {
            get {
                return ResourceManager.GetString("FechaUltimaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últ. Visita.
        /// </summary>
        public static string FechaUltimaVisita {
            get {
                return ResourceManager.GetString("FechaUltimaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        public static string Frecuencia {
            get {
                return ResourceManager.GetString("Frecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocerca.
        /// </summary>
        public static string Geocerca {
            get {
                return ResourceManager.GetString("Geocerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiones.
        /// </summary>
        public static string Gestiones {
            get {
                return ResourceManager.GetString("Gestiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Fin.
        /// </summary>
        public static string HoraFin {
            get {
                return ResourceManager.GetString("HoraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin Jornada.
        /// </summary>
        public static string HoraFinJornada {
            get {
                return ResourceManager.GetString("HoraFinJornada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de Fin de Tracking.
        /// </summary>
        public static string HoraFinTracking {
            get {
                return ResourceManager.GetString("HoraFinTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Inicio.
        /// </summary>
        public static string HoraInicio {
            get {
                return ResourceManager.GetString("HoraInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1era Jornada.
        /// </summary>
        public static string HoraInicioPrimeraJornada {
            get {
                return ResourceManager.GetString("HoraInicioPrimeraJornada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2da Jornada.
        /// </summary>
        public static string HoraInicioSegundaJornada {
            get {
                return ResourceManager.GetString("HoraInicioSegundaJornada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de Inicio de Tracking.
        /// </summary>
        public static string HoraInicioTracking {
            get {
                return ResourceManager.GetString("HoraInicioTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Primer Reporte.
        /// </summary>
        public static string HoraPrimerReporte {
            get {
                return ResourceManager.GetString("HoraPrimerReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas Laborables.
        /// </summary>
        public static string HorasJornadaLaboral {
            get {
                return ResourceManager.GetString("HorasJornadaLaboral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Último Reporte.
        /// </summary>
        public static string HoraUltimoReporte {
            get {
                return ResourceManager.GetString("HoraUltimoReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy.
        /// </summary>
        public static string Hoy {
            get {
                return ResourceManager.GetString("Hoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string Identificacion {
            get {
                return ResourceManager.GetString("Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importancia.
        /// </summary>
        public static string Importancia {
            get {
                return ResourceManager.GetString("Importancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string Importe {
            get {
                return ResourceManager.GetString("Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir Cliente(s).
        /// </summary>
        public static string IncluirCliente {
            get {
                return ResourceManager.GetString("IncluirCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string IncluirClientes {
            get {
                return ResourceManager.GetString("IncluirClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión.
        /// </summary>
        public static string IncluirGestion {
            get {
                return ResourceManager.GetString("IncluirGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorrido.
        /// </summary>
        public static string IncluirRecorrido {
            get {
                return ResourceManager.GetString("IncluirRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración Promedio.
        /// </summary>
        public static string IndicadorDuracionVisitaPromedio {
            get {
                return ResourceManager.GetString("IndicadorDuracionVisitaPromedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitados.
        /// </summary>
        public static string IndicadorGestionados {
            get {
                return ResourceManager.GetString("IndicadorGestionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Visitados.
        /// </summary>
        public static string IndicadorNoGestionados {
            get {
                return ResourceManager.GetString("IndicadorNoGestionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximos.
        /// </summary>
        public static string IndicadorProximos {
            get {
                return ResourceManager.GetString("IndicadorProximos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitas.
        /// </summary>
        public static string IndicadorTotalGestiones {
            get {
                return ResourceManager.GetString("IndicadorTotalGestiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice Actividad.
        /// </summary>
        public static string IndiceActividad {
            get {
                return ResourceManager.GetString("IndiceActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice Actividad 30.
        /// </summary>
        public static string IndiceActividad1 {
            get {
                return ResourceManager.GetString("IndiceActividad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice Actividad 90.
        /// </summary>
        public static string IndiceActividad2 {
            get {
                return ResourceManager.GetString("IndiceActividad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Actividades.
        /// </summary>
        public static string InicioActividad {
            get {
                return ResourceManager.GetString("InicioActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo de Minutos en Tracking.
        /// </summary>
        public static string IntervaloMinutos {
            get {
                return ResourceManager.GetString("IntervaloMinutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera Jornada.
        /// </summary>
        public static string Jornada1 {
            get {
                return ResourceManager.GetString("Jornada1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda Jornada.
        /// </summary>
        public static string Jornada2 {
            get {
                return ResourceManager.GetString("Jornada2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kms.
        /// </summary>
        public static string Kms {
            get {
                return ResourceManager.GetString("Kms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitud.
        /// </summary>
        public static string Latitud {
            get {
                return ResourceManager.GetString("Latitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite.
        /// </summary>
        public static string Limite {
            get {
                return ResourceManager.GetString("Limite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea de Tiempo.
        /// </summary>
        public static string LineaTiempo {
            get {
                return ResourceManager.GetString("LineaTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        public static string Listado {
            get {
                return ResourceManager.GetString("Listado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud.
        /// </summary>
        public static string Longitud {
            get {
                return ResourceManager.GetString("Longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote.
        /// </summary>
        public static string Lote {
            get {
                return ResourceManager.GetString("Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotes.
        /// </summary>
        public static string Lotes {
            get {
                return ResourceManager.GetString("Lotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar de Marcación.
        /// </summary>
        public static string LugarMarcacion {
            get {
                return ResourceManager.GetString("LugarMarcacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar Planificado.
        /// </summary>
        public static string LugarPlanificado {
            get {
                return ResourceManager.GetString("LugarPlanificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mañana.
        /// </summary>
        public static string Maniana {
            get {
                return ResourceManager.GetString("Maniana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutos.
        /// </summary>
        public static string Minutos {
            get {
                return ResourceManager.GetString("Minutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Fotos.
        /// </summary>
        public static string MostrarFotos {
            get {
                return ResourceManager.GetString("MostrarFotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string Motivo {
            get {
                return ResourceManager.GetString("Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        public static string Movil {
            get {
                return ResourceManager.GetString("Movil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movilización.
        /// </summary>
        public static string Movilizacion {
            get {
                return ResourceManager.GetString("Movilizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento.
        /// </summary>
        public static string Movimiento {
            get {
                return ResourceManager.GetString("Movimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo es necesario cuando reprograma la Visita.
        /// </summary>
        public static string NecesarioMotivoReprogramacion {
            get {
                return ResourceManager.GetString("NecesarioMotivoReprogramacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aplica marcación.
        /// </summary>
        public static string NoAplicaMarcacion {
            get {
                return ResourceManager.GetString("NoAplicaMarcacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Editable.
        /// </summary>
        public static string NoEditable {
            get {
                return ResourceManager.GetString("NoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre1 {
            get {
                return ResourceManager.GetString("Nombre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Nombre.
        /// </summary>
        public static string Nombre2 {
            get {
                return ResourceManager.GetString("Nombre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Nombres {
            get {
                return ResourceManager.GetString("Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Clientes.
        /// </summary>
        public static string NumClientes {
            get {
                return ResourceManager.GetString("NumClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Visitas.
        /// </summary>
        public static string NumeroGestiones {
            get {
                return ResourceManager.GetString("NumeroGestiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Gestiones.
        /// </summary>
        public static string NumGestiones {
            get {
                return ResourceManager.GetString("NumGestiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Preguntas.
        /// </summary>
        public static string NumPreguntas {
            get {
                return ResourceManager.GetString("NumPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de Respuestas.
        /// </summary>
        public static string NumRepuestas {
            get {
                return ResourceManager.GetString("NumRepuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        public static string Observacion {
            get {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación Supervisor.
        /// </summary>
        public static string ObservacionSupervisor {
            get {
                return ResourceManager.GetString("ObservacionSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre cada.
        /// </summary>
        public static string Ocurrencia {
            get {
                return ResourceManager.GetString("Ocurrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opción.
        /// </summary>
        public static string Opcion {
            get {
                return ResourceManager.GetString("Opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidad.
        /// </summary>
        public static string Oportunidad {
            get {
                return ResourceManager.GetString("Oportunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otras.
        /// </summary>
        public static string Otras {
            get {
                return ResourceManager.GetString("Otras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páginas.
        /// </summary>
        public static string Paginas {
            get {
                return ResourceManager.GetString("Paginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Web.
        /// </summary>
        public static string PaginaWeb {
            get {
                return ResourceManager.GetString("PaginaWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de Paradas.
        /// </summary>
        public static string Paradas {
            get {
                return ResourceManager.GetString("Paradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso.
        /// </summary>
        public static string Permiso {
            get {
                return ResourceManager.GetString("Permiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso Previo.
        /// </summary>
        public static string PermisoPrevio {
            get {
                return ResourceManager.GetString("PermisoPrevio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir la creación de nuevos clientes.
        /// </summary>
        public static string PermitirCreacionClientes {
            get {
                return ResourceManager.GetString("PermitirCreacionClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir modificar la información de los clientes.
        /// </summary>
        public static string PermitirModificacionClientes {
            get {
                return ResourceManager.GetString("PermitirModificacionClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string Persona {
            get {
                return ResourceManager.GetString("Persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona Jurídica.
        /// </summary>
        public static string PersonaJuridica {
            get {
                return ResourceManager.GetString("PersonaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona Natural.
        /// </summary>
        public static string PersonaNatural {
            get {
                return ResourceManager.GetString("PersonaNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefijo Telefónico.
        /// </summary>
        public static string PrefijoTelefonico {
            get {
                return ResourceManager.GetString("PrefijoTelefonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas.
        /// </summary>
        public static string Preguntas {
            get {
                return ResourceManager.GetString("Preguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera Gestión.
        /// </summary>
        public static string PrimeraGestion {
            get {
                return ResourceManager.GetString("PrimeraGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probabilidad.
        /// </summary>
        public static string Probabilidad {
            get {
                return ResourceManager.GetString("Probabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación.
        /// </summary>
        public static string Programacion {
            get {
                return ResourceManager.GetString("Programacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación de Rutas.
        /// </summary>
        public static string ProgramacionRuta {
            get {
                return ResourceManager.GetString("ProgramacionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación de Tareas.
        /// </summary>
        public static string ProgramacionTarea {
            get {
                return ResourceManager.GetString("ProgramacionTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospecto.
        /// </summary>
        public static string Prospecto {
            get {
                return ResourceManager.GetString("Prospecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasignar.
        /// </summary>
        public static string Reasignar {
            get {
                return ResourceManager.GetString("Reasignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string Rechazar {
            get {
                return ResourceManager.GetString("Rechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string RecorridoAlerta {
            get {
                return ResourceManager.GetString("RecorridoAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación Reportada.
        /// </summary>
        public static string RecorridoCheckPoint {
            get {
                return ResourceManager.GetString("RecorridoCheckPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Región.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string Registros {
            get {
                return ResourceManager.GetString("Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string Regresar {
            get {
                return ResourceManager.GetString("Regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitente.
        /// </summary>
        public static string Remitente {
            get {
                return ResourceManager.GetString("Remitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover {
            get {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Gestión.
        /// </summary>
        public static string ReporteGestion {
            get {
                return ResourceManager.GetString("ReporteGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representante Legal.
        /// </summary>
        public static string RepresentanteLegal {
            get {
                return ResourceManager.GetString("RepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula Repr. Legal.
        /// </summary>
        public static string RepresentateLegalIdentificacion {
            get {
                return ResourceManager.GetString("RepresentateLegalIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas.
        /// </summary>
        public static string Respuestas {
            get {
                return ResourceManager.GetString("Respuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        public static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunión.
        /// </summary>
        public static string Reunion {
            get {
                return ResourceManager.GetString("Reunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversar.
        /// </summary>
        public static string Reversar {
            get {
                return ResourceManager.GetString("Reversar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia Mínima entre Trackings.
        /// </summary>
        public static string RouteDistance {
            get {
                return ResourceManager.GetString("RouteDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        public static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutas.
        /// </summary>
        public static string Rutas {
            get {
                return ResourceManager.GetString("Rutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Agente.
        /// </summary>
        public static string SeleccionarAgente {
            get {
                return ResourceManager.GetString("SeleccionarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Calendario.
        /// </summary>
        public static string SeleccionarCalendario {
            get {
                return ResourceManager.GetString("SeleccionarCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Canal.
        /// </summary>
        public static string SeleccionarCanal {
            get {
                return ResourceManager.GetString("SeleccionarCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Cargo.
        /// </summary>
        public static string SeleccionarCargo {
            get {
                return ResourceManager.GetString("SeleccionarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Categoría.
        /// </summary>
        public static string SeleccionarCategoria {
            get {
                return ResourceManager.GetString("SeleccionarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Ciudad.
        /// </summary>
        public static string SeleccionarCiudad {
            get {
                return ResourceManager.GetString("SeleccionarCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Dirección.
        /// </summary>
        public static string SeleccionarDireccion {
            get {
                return ResourceManager.GetString("SeleccionarDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Grupo.
        /// </summary>
        public static string SeleccionarGrupo {
            get {
                return ResourceManager.GetString("SeleccionarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Motivo de Reprogramación.
        /// </summary>
        public static string SeleccionarMotivoReprogramacion {
            get {
                return ResourceManager.GetString("SeleccionarMotivoReprogramacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Región.
        /// </summary>
        public static string SeleccionarRegion {
            get {
                return ResourceManager.GetString("SeleccionarRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una Ruta.
        /// </summary>
        public static string SeleccionarRuta {
            get {
                return ResourceManager.GetString("SeleccionarRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Supervisor.
        /// </summary>
        public static string SeleccionarSupervisor {
            get {
                return ResourceManager.GetString("SeleccionarSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Tipo de Cliente.
        /// </summary>
        public static string SeleccionarTipoCliente {
            get {
                return ResourceManager.GetString("SeleccionarTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Tipo de Identificación.
        /// </summary>
        public static string SeleccionarTipoIdentificacion {
            get {
                return ResourceManager.GetString("SeleccionarTipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Usuario.
        /// </summary>
        public static string SeleccionarUsuario {
            get {
                return ResourceManager.GetString("SeleccionarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        public static string Semana {
            get {
                return ResourceManager.GetString("Semana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana Laboral.
        /// </summary>
        public static string SemanaLaboral {
            get {
                return ResourceManager.GetString("SemanaLaboral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sin Especificar).
        /// </summary>
        public static string SinEspecificar {
            get {
                return ResourceManager.GetString("SinEspecificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin iniciar.
        /// </summary>
        public static string SinIniciar {
            get {
                return ResourceManager.GetString("SinIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitante.
        /// </summary>
        public static string Solicitante {
            get {
                return ResourceManager.GetString("Solicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoría.
        /// </summary>
        public static string SubCategoria {
            get {
                return ResourceManager.GetString("SubCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string Tarea {
            get {
                return ResourceManager.GetString("Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareas.
        /// </summary>
        public static string Tareas {
            get {
                return ResourceManager.GetString("Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareas ya asignadas.
        /// </summary>
        public static string TareasYaAsignadas {
            get {
                return ResourceManager.GetString("TareasYaAsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo.
        /// </summary>
        public static string Tiempo {
            get {
                return ResourceManager.GetString("Tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Detenido.
        /// </summary>
        public static string TiempoDetenido {
            get {
                return ResourceManager.GetString("TiempoDetenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Inactividad.
        /// </summary>
        public static string TiempoInactividad {
            get {
                return ResourceManager.GetString("TiempoInactividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Movimiento.
        /// </summary>
        public static string TiempoRecorrido {
            get {
                return ResourceManager.GetString("TiempoRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de Movilización Default.
        /// </summary>
        public static string TiempoRutaDefault {
            get {
                return ResourceManager.GetString("TiempoRutaDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene Fin.
        /// </summary>
        public static string TieneFechaFin {
            get {
                return ResourceManager.GetString("TieneFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplica Ubicación.
        /// </summary>
        public static string TieneUbicacion {
            get {
                return ResourceManager.GetString("TieneUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Mínimo Parada.
        /// </summary>
        public static string TimpoMinimoParada {
            get {
                return ResourceManager.GetString("TimpoMinimoParada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Actividad.
        /// </summary>
        public static string TipoActividad {
            get {
                return ResourceManager.GetString("TipoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cartera.
        /// </summary>
        public static string TipoCartera {
            get {
                return ResourceManager.GetString("TipoCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cliente.
        /// </summary>
        public static string TipoCliente {
            get {
                return ResourceManager.GetString("TipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos Cliente.
        /// </summary>
        public static string TipoClientes {
            get {
                return ResourceManager.GetString("TipoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Dirección.
        /// </summary>
        public static string TipoDireccion {
            get {
                return ResourceManager.GetString("TipoDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Identificación.
        /// </summary>
        public static string TipoIdentificacion {
            get {
                return ResourceManager.GetString("TipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Persona.
        /// </summary>
        public static string TipoPersona {
            get {
                return ResourceManager.GetString("TipoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Tarea.
        /// </summary>
        public static string TipoTarea {
            get {
                return ResourceManager.GetString("TipoTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareas de este tipo ya asignadas a la ruta.
        /// </summary>
        public static string TipoTareaAsignada {
            get {
                return ResourceManager.GetString("TipoTareaAsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los Clientes.
        /// </summary>
        public static string TodosClientes {
            get {
                return ResourceManager.GetString("TodosClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los años.
        /// </summary>
        public static string TodosLosAños {
            get {
                return ResourceManager.GetString("TodosLosAños", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos mis Agentes.
        /// </summary>
        public static string TodosMisAgentes {
            get {
                return ResourceManager.GetString("TodosMisAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación Matriz.
        /// </summary>
        public static string UbicacionMatriz {
            get {
                return ResourceManager.GetString("UbicacionMatriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de Marcación.
        /// </summary>
        public static string UbicacionPartidaAgentes {
            get {
                return ResourceManager.GetString("UbicacionPartidaAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Gestión.
        /// </summary>
        public static string UltimaGestion {
            get {
                return ResourceManager.GetString("UltimaGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hora.
        /// </summary>
        public static string UnaHora {
            get {
                return ResourceManager.GetString("UnaHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total.
        /// </summary>
        public static string ValorTotal {
            get {
                return ResourceManager.GetString("ValorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Unitario.
        /// </summary>
        public static string ValorUnitario {
            get {
                return ResourceManager.GetString("ValorUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Pedido.
        /// </summary>
        public static string VerPedido {
            get {
                return ResourceManager.GetString("VerPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigente desde.
        /// </summary>
        public static string VigenciaDesde {
            get {
                return ResourceManager.GetString("VigenciaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigente Hasta.
        /// </summary>
        public static string VigenciaHasta {
            get {
                return ResourceManager.GetString("VigenciaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinida.
        /// </summary>
        public static string VigenciaIndefinida {
            get {
                return ResourceManager.GetString("VigenciaIndefinida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigente.
        /// </summary>
        public static string Vigente {
            get {
                return ResourceManager.GetString("Vigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia Mínima entre Visitas.
        /// </summary>
        public static string VisitDistance {
            get {
                return ResourceManager.GetString("VisitDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de la Zona.
        /// </summary>
        public static string ZonaDetalle {
            get {
                return ResourceManager.GetString("ZonaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonas.
        /// </summary>
        public static string Zonas {
            get {
                return ResourceManager.GetString("Zonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movilización Promedio.
        /// </summary>
        public static string ZonaTiempoMovilizacion {
            get {
                return ResourceManager.GetString("ZonaTiempoMovilizacion", resourceCulture);
            }
        }
    }
}
