//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rp3.AgendaComercial.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LegendFor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LegendFor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rp3.AgendaComercial.Resources.LegendFor", typeof(LegendFor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las activades de grupos no pueden estar dentro de otro grupo.
        /// </summary>
        public static string ActividadGrupoPadre {
            get {
                return ResourceManager.GetString("ActividadGrupoPadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo pueden tener detalles las actividades de grupo.
        /// </summary>
        public static string ActividadNoGrupoHijo {
            get {
                return ResourceManager.GetString("ActividadNoGrupoHijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La actividad ha sido procesada exitosamente.
        /// </summary>
        public static string ActividadProcesada {
            get {
                return ResourceManager.GetString("ActividadProcesada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La agenda de la ruta ha sido procesada exitosamente.
        /// </summary>
        public static string AgendaProcesada {
            get {
                return ResourceManager.GetString("AgendaProcesada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el agente.
        /// </summary>
        public static string Agente {
            get {
                return ResourceManager.GetString("Agente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del agente a agregar.
        /// </summary>
        public static string AgenteToken {
            get {
                return ResourceManager.GetString("AgenteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visita Realizada a {0} {1} del Destino.
        /// </summary>
        public static string AlertaVisitaRealizadaNDistanciaDestino {
            get {
                return ResourceManager.GetString("AlertaVisitaRealizadaNDistanciaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del canal a agregar.
        /// </summary>
        public static string CanalToken {
            get {
                return ResourceManager.GetString("CanalToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del cliente a buscar.
        /// </summary>
        public static string ClienteBuscar {
            get {
                return ResourceManager.GetString("ClienteBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el contacto.
        /// </summary>
        public static string ClienteContacto {
            get {
                return ResourceManager.GetString("ClienteContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del cliente a excluir.
        /// </summary>
        public static string ClienteExcluir {
            get {
                return ResourceManager.GetString("ClienteExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del cliente a incluir.
        /// </summary>
        public static string ClienteIncluir {
            get {
                return ResourceManager.GetString("ClienteIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del cliente a agregar.
        /// </summary>
        public static string ClienteToken {
            get {
                return ResourceManager.GetString("ClienteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor corrija todos los errores.
        /// </summary>
        public static string CorregirErrores {
            get {
                return ResourceManager.GetString("CorregirErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to día(s)..
        /// </summary>
        public static string Dias {
            get {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días No Laborables.
        /// </summary>
        public static string DiasNoLaborables {
            get {
                return ResourceManager.GetString("DiasNoLaborables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminará la Dirección seleccionada.
        /// </summary>
        public static string EliminarDireccionSeleccionada {
            get {
                return ResourceManager.GetString("EliminarDireccionSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastre el marcador hasta el lugar donde se encuentra la ubicación.
        /// </summary>
        public static string EstablecerUbicacion {
            get {
                return ResourceManager.GetString("EstablecerUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el texto de la opción.
        /// </summary>
        public static string IngreseTextoOpcion {
            get {
                return ResourceManager.GetString("IngreseTextoOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El lote ha sido procesado exitosamente.
        /// </summary>
        public static string LoteProcesado {
            get {
                return ResourceManager.GetString("LoteProcesado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del lote a agregar.
        /// </summary>
        public static string LoteToken {
            get {
                return ResourceManager.GetString("LoteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No se han definido programaciones).
        /// </summary>
        public static string NoExistenProgramaciones {
            get {
                return ResourceManager.GetString("NoExistenProgramaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la razón social.
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta ha sido procesada exitosamente.
        /// </summary>
        public static string RutaProcesada {
            get {
                return ResourceManager.GetString("RutaProcesada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija un Agente para revisar su Agenda.
        /// </summary>
        public static string SeleccioneAgenteAgenda {
            get {
                return ResourceManager.GetString("SeleccioneAgenteAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de Agente.
        /// </summary>
        public static string SeleccioneAgenteAgendaTitulo {
            get {
                return ResourceManager.GetString("SeleccioneAgenteAgendaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija un Agente para revisar sus Oportunidades.
        /// </summary>
        public static string SeleccioneAgenteOportunidad {
            get {
                return ResourceManager.GetString("SeleccioneAgenteOportunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el Rol que utilizará en esta sesión.
        /// </summary>
        public static string SeleccioneRol {
            get {
                return ResourceManager.GetString("SeleccioneRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semana(s) en.
        /// </summary>
        public static string Semanas {
            get {
                return ResourceManager.GetString("Semanas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarea ha sido procesada exitosamente.
        /// </summary>
        public static string TareaProcesada {
            get {
                return ResourceManager.GetString("TareaProcesada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoga las tareas que serán realizadas en durante esta Etapa en cada Oportunidad..
        /// </summary>
        public static string TareasEnEtapa {
            get {
                return ResourceManager.GetString("TareasEnEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre de la tarea a agendar.
        /// </summary>
        public static string TareaToken {
            get {
                return ResourceManager.GetString("TareaToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el canal.
        /// </summary>
        public static string TextCanal {
            get {
                return ResourceManager.GetString("TextCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el tipo de cliente.
        /// </summary>
        public static string TextTipoCliente {
            get {
                return ResourceManager.GetString("TextTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la zona.
        /// </summary>
        public static string TextZona {
            get {
                return ResourceManager.GetString("TextZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre del tipo de cliente a agregar.
        /// </summary>
        public static string TipoClienteToken {
            get {
                return ResourceManager.GetString("TipoClienteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica la ubicación de la oficina matriz, la cual se toma como referencia para la generación de rutas.
        /// </summary>
        public static string UsoUbicacionMatriz {
            get {
                return ResourceManager.GetString("UsoUbicacionMatriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visita Realizada en el lugar de Destino.
        /// </summary>
        public static string VisitaRealizadaEnDestino {
            get {
                return ResourceManager.GetString("VisitaRealizadaEnDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el nombre de la zona a agregar.
        /// </summary>
        public static string ZonaToken {
            get {
                return ResourceManager.GetString("ZonaToken", resourceCulture);
            }
        }
    }
}
