//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rp3.AgendaComercial.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageFor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageFor() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rp3.AgendaComercial.Resources.MessageFor", typeof(MessageFor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo subido correctamente.
        /// </summary>
        public static string ArchivoSubidoCorrectamente {
            get {
                return ResourceManager.GetString("ArchivoSubidoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arraste aquí los clientes a remover de la Ruta.
        /// </summary>
        public static string ArrasteClientesRemoverRuta {
            get {
                return ResourceManager.GetString("ArrasteClientesRemoverRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación del Cliente no ha sido especificada.
        /// </summary>
        public static string ClienteSinUbicacion {
            get {
                return ResourceManager.GetString("ClienteSinUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar?.
        /// </summary>
        public static string ConfirmarEliminar {
            get {
                return ResourceManager.GetString("ConfirmarEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre {0} . Empieza {1}.
        /// </summary>
        public static string DescripcionDiaria {
            get {
                return ResourceManager.GetString("DescripcionDiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre cada día {0} de {1}. Empieza {2}.
        /// </summary>
        public static string DescripcionMensualDia {
            get {
                return ResourceManager.GetString("DescripcionMensualDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre el {0} {1} de {2}. Empieza {3}.
        /// </summary>
        public static string DescripcionMensualEl {
            get {
                return ResourceManager.GetString("DescripcionMensualEl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurre {0} de {1}. Empieza {2}.
        /// </summary>
        public static string DescripcionSemanal {
            get {
                return ResourceManager.GetString("DescripcionSemanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  hasta {0}..
        /// </summary>
        public static string DescripcionSinFin {
            get {
                return ResourceManager.GetString("DescripcionSinFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminará la Dirección seleccionada.
        /// </summary>
        public static string EliminarDireccionSeleccionada {
            get {
                return ResourceManager.GetString("EliminarDireccionSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La foto ha sido eliminada.
        /// </summary>
        public static string EliminarImageOk {
            get {
                return ResourceManager.GetString("EliminarImageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La foto no se ha podido eliminar.
        /// </summary>
        public static string ErrorEliminarFoto {
            get {
                return ResourceManager.GetString("ErrorEliminarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba el nombre de la Tarea.
        /// </summary>
        public static string EscribaNombreTarea {
            get {
                return ResourceManager.GetString("EscribaNombreTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Inicio de Actividad no puede ser mayor a hoy.
        /// </summary>
        public static string FechaInicioActividadMayorHoy {
            get {
                return ResourceManager.GetString("FechaInicioActividadMayorHoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Nacimiento no puede ser mayor a hoy.
        /// </summary>
        public static string FechaNacimientoMayorHoy {
            get {
                return ResourceManager.GetString("FechaNacimientoMayorHoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Fin debe ser mayor al Inicio.
        /// </summary>
        public static string FinMayorAInicio {
            get {
                return ResourceManager.GetString("FinMayorAInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación no fue captada durante la visita.
        /// </summary>
        public static string GestionSinUbicacion {
            get {
                return ResourceManager.GetString("GestionSinUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hace {0} día(s)..
        /// </summary>
        public static string HaceDias {
            get {
                return ResourceManager.GetString("HaceDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hace {0} hora(s)..
        /// </summary>
        public static string HaceHoras {
            get {
                return ResourceManager.GetString("HaceHoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hace {0} minuto(s)..
        /// </summary>
        public static string HaceMinutos {
            get {
                return ResourceManager.GetString("HaceMinutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Identificación Incorrecta.
        /// </summary>
        public static string IdentificacionIncorrecta {
            get {
                return ResourceManager.GetString("IdentificacionIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud de la identificación ingresada ({0}) no coincide con la requeridad para el tipo {1} ({2})..
        /// </summary>
        public static string IdentificacionLongitudIncorrecta {
            get {
                return ResourceManager.GetString("IdentificacionLongitudIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Identificación ingresada ya existe.
        /// </summary>
        public static string IdentificacionRepetida {
            get {
                return ResourceManager.GetString("IdentificacionRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La identificación ingresada no cumple con las validaciones para el tipo {0}..
        /// </summary>
        public static string IdentificacionValidacionIncorrecta {
            get {
                return ResourceManager.GetString("IdentificacionValidacionIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Inicio debe ser menor al Fin.
        /// </summary>
        public static string InicioMenorAFin {
            get {
                return ResourceManager.GetString("InicioMenorAFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene marcaciones fuera del área planificada.
        /// </summary>
        public static string MarcacionesFueraArea {
            get {
                return ResourceManager.GetString("MarcacionesFueraArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una fotografía para borrar.
        /// </summary>
        public static string NoExisteFotoEliminar {
            get {
                return ResourceManager.GetString("NoExisteFotoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen Contactos.
        /// </summary>
        public static string NoExistenContactos {
            get {
                return ResourceManager.GetString("NoExistenContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen Direcciones.
        /// </summary>
        public static string NoExistenDirecciones {
            get {
                return ResourceManager.GetString("NoExistenDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha ingresado ninguna Tarea.
        /// </summary>
        public static string NoHaIngresadoTarea {
            get {
                return ResourceManager.GetString("NoHaIngresadoTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar el archivo.
        /// </summary>
        public static string NoPudoCargarArchivo {
            get {
                return ResourceManager.GetString("NoPudoCargarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar la fotografía.
        /// </summary>
        public static string NoPudoCargarFoto {
            get {
                return ResourceManager.GetString("NoPudoCargarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Ubicación del Prospecto no ha sido especificada.
        /// </summary>
        public static string ProspectoSinUbicacion {
            get {
                return ResourceManager.GetString("ProspectoSinUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo debe ingresar números.
        /// </summary>
        public static string SoloNumeros {
            get {
                return ResourceManager.GetString("SoloNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de la fotografía es muy grande. Elija otro archivo. Solo se permiten {0} MB por fotografía..
        /// </summary>
        public static string TamanoFotoExcedido {
            get {
                return ResourceManager.GetString("TamanoFotoExcedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las Actividades de esta Tarea no pueden ser modificadas debido a que está siendo usada.
        /// </summary>
        public static string TareaNoEditable {
            get {
                return ResourceManager.GetString("TareaNoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene Permisos o Justificaciones Solicitadas.
        /// </summary>
        public static string TienePermisos {
            get {
                return ResourceManager.GetString("TienePermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe el ingresar el campo {0}.
        /// </summary>
        public static string ValidacionCampoObligatorio {
            get {
                return ResourceManager.GetString("ValidacionCampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor debe estar comprendido entre {0:n0} y {1:n0}.
        /// </summary>
        public static string ValorComprendidoEntre {
            get {
                return ResourceManager.GetString("ValorComprendidoEntre", resourceCulture);
            }
        }
    }
}
