//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rp3.AgendaComercial.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitleFor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleFor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rp3.AgendaComercial.Resources.TitleFor", typeof(TitleFor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        public static string Actividades {
            get {
                return ResourceManager.GetString("Actividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        public static string Agente {
            get {
                return ResourceManager.GetString("Agente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Gestión de Agentes.
        /// </summary>
        public static string AgenteReporteGestion {
            get {
                return ResourceManager.GetString("AgenteReporteGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentes.
        /// </summary>
        public static string Agentes {
            get {
                return ResourceManager.GetString("Agentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis de Agentes.
        /// </summary>
        public static string AnalisisAgentes {
            get {
                return ResourceManager.GetString("AnalisisAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistentes.
        /// </summary>
        public static string Asistentes {
            get {
                return ResourceManager.GetString("Asistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornada Laboral.
        /// </summary>
        public static string Calendario {
            get {
                return ResourceManager.GetString("Calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal.
        /// </summary>
        public static string Canal {
            get {
                return ResourceManager.GetString("Canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canales.
        /// </summary>
        public static string Canales {
            get {
                return ResourceManager.GetString("Canales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos.
        /// </summary>
        public static string Cargos {
            get {
                return ResourceManager.GetString("Cargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías.
        /// </summary>
        public static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudades.
        /// </summary>
        public static string Ciudades {
            get {
                return ResourceManager.GetString("Ciudades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes por Ruta.
        /// </summary>
        public static string ClienteRuta {
            get {
                return ResourceManager.GetString("ClienteRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes por Programar.
        /// </summary>
        public static string ClientesProgramar {
            get {
                return ResourceManager.GetString("ClientesProgramar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Ruta.
        /// </summary>
        public static string ConfigurarRuta {
            get {
                return ResourceManager.GetString("ConfigurarRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Tarea.
        /// </summary>
        public static string ConfigurarTarea {
            get {
                return ResourceManager.GetString("ConfigurarTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string Contactos {
            get {
                return ResourceManager.GetString("Contactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Agente.
        /// </summary>
        public static string CrearAgente {
            get {
                return ResourceManager.GetString("CrearAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Calendario.
        /// </summary>
        public static string CrearCalendario {
            get {
                return ResourceManager.GetString("CrearCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Canal.
        /// </summary>
        public static string CrearCanal {
            get {
                return ResourceManager.GetString("CrearCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cargo.
        /// </summary>
        public static string CrearCargo {
            get {
                return ResourceManager.GetString("CrearCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Categoría.
        /// </summary>
        public static string CrearCategoria {
            get {
                return ResourceManager.GetString("CrearCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cliente.
        /// </summary>
        public static string CrearCliente {
            get {
                return ResourceManager.GetString("CrearCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Etapa.
        /// </summary>
        public static string CrearEtapa {
            get {
                return ResourceManager.GetString("CrearEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Grupo.
        /// </summary>
        public static string CrearGrupo {
            get {
                return ResourceManager.GetString("CrearGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Lote.
        /// </summary>
        public static string CrearLote {
            get {
                return ResourceManager.GetString("CrearLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Memo.
        /// </summary>
        public static string CrearMemo {
            get {
                return ResourceManager.GetString("CrearMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Producto.
        /// </summary>
        public static string CrearProducto {
            get {
                return ResourceManager.GetString("CrearProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Programación.
        /// </summary>
        public static string CrearProgramacionRuta {
            get {
                return ResourceManager.GetString("CrearProgramacionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Programación.
        /// </summary>
        public static string CrearProgramacionTarea {
            get {
                return ResourceManager.GetString("CrearProgramacionTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Región.
        /// </summary>
        public static string CrearRegion {
            get {
                return ResourceManager.GetString("CrearRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Reunión.
        /// </summary>
        public static string CrearReunion {
            get {
                return ResourceManager.GetString("CrearReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Ruta.
        /// </summary>
        public static string CrearRuta {
            get {
                return ResourceManager.GetString("CrearRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Subcategoría.
        /// </summary>
        public static string CrearSubCategoria {
            get {
                return ResourceManager.GetString("CrearSubCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Supervisor.
        /// </summary>
        public static string CrearSupervisor {
            get {
                return ResourceManager.GetString("CrearSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tarea.
        /// </summary>
        public static string CrearTarea {
            get {
                return ResourceManager.GetString("CrearTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tipo de Actividad.
        /// </summary>
        public static string CrearTipoActividad {
            get {
                return ResourceManager.GetString("CrearTipoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tipo de Cartera.
        /// </summary>
        public static string CrearTipoCartera {
            get {
                return ResourceManager.GetString("CrearTipoCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tipo de Cliente.
        /// </summary>
        public static string CrearTipoCliente {
            get {
                return ResourceManager.GetString("CrearTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Zona.
        /// </summary>
        public static string CrearZona {
            get {
                return ResourceManager.GetString("CrearZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        public static string DatosGenerales {
            get {
                return ResourceManager.GetString("DatosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        public static string Descuento {
            get {
                return ResourceManager.GetString("Descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatarios.
        /// </summary>
        public static string Destinatarios {
            get {
                return ResourceManager.GetString("Destinatarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Agente.
        /// </summary>
        public static string DetalleAgente {
            get {
                return ResourceManager.GetString("DetalleAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Calendario.
        /// </summary>
        public static string DetalleCalendario {
            get {
                return ResourceManager.GetString("DetalleCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Canal.
        /// </summary>
        public static string DetalleCanal {
            get {
                return ResourceManager.GetString("DetalleCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Cargo.
        /// </summary>
        public static string DetalleCargo {
            get {
                return ResourceManager.GetString("DetalleCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Categoría.
        /// </summary>
        public static string DetalleCategoria {
            get {
                return ResourceManager.GetString("DetalleCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Cliente.
        /// </summary>
        public static string DetalleCliente {
            get {
                return ResourceManager.GetString("DetalleCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Etapa.
        /// </summary>
        public static string DetalleEtapa {
            get {
                return ResourceManager.GetString("DetalleEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Grupo.
        /// </summary>
        public static string DetalleGrupo {
            get {
                return ResourceManager.GetString("DetalleGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Lote.
        /// </summary>
        public static string DetalleLote {
            get {
                return ResourceManager.GetString("DetalleLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Memo.
        /// </summary>
        public static string DetalleMemo {
            get {
                return ResourceManager.GetString("DetalleMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Programación.
        /// </summary>
        public static string DetalleProgramacionRuta {
            get {
                return ResourceManager.GetString("DetalleProgramacionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Programación.
        /// </summary>
        public static string DetalleProgramacionTarea {
            get {
                return ResourceManager.GetString("DetalleProgramacionTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Región.
        /// </summary>
        public static string DetalleRegion {
            get {
                return ResourceManager.GetString("DetalleRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Reunión.
        /// </summary>
        public static string DetalleReunion {
            get {
                return ResourceManager.GetString("DetalleReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Ruta.
        /// </summary>
        public static string DetalleRuta {
            get {
                return ResourceManager.GetString("DetalleRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes de la Ruta.
        /// </summary>
        public static string DetalleRutaCliente {
            get {
                return ResourceManager.GetString("DetalleRutaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Subcategoría.
        /// </summary>
        public static string DetalleSubcategoria {
            get {
                return ResourceManager.GetString("DetalleSubcategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Supervisor.
        /// </summary>
        public static string DetalleSupervisor {
            get {
                return ResourceManager.GetString("DetalleSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Tarea.
        /// </summary>
        public static string DetalleTarea {
            get {
                return ResourceManager.GetString("DetalleTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Tipo de Actividad.
        /// </summary>
        public static string DetalleTipoActividad {
            get {
                return ResourceManager.GetString("DetalleTipoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Tipo de Cartera.
        /// </summary>
        public static string DetalleTipoCartera {
            get {
                return ResourceManager.GetString("DetalleTipoCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Tipo de Cliente.
        /// </summary>
        public static string DetalleTipoCliente {
            get {
                return ResourceManager.GetString("DetalleTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Zona.
        /// </summary>
        public static string DetalleZona {
            get {
                return ResourceManager.GetString("DetalleZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Laborables.
        /// </summary>
        public static string DiasLaborales {
            get {
                return ResourceManager.GetString("DiasLaborales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jornadas No Laborables.
        /// </summary>
        public static string DiasNoLaborables {
            get {
                return ResourceManager.GetString("DiasNoLaborables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        public static string Direcciones {
            get {
                return ResourceManager.GetString("Direcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Agente.
        /// </summary>
        public static string EditarAgente {
            get {
                return ResourceManager.GetString("EditarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Calendario.
        /// </summary>
        public static string EditarCalendario {
            get {
                return ResourceManager.GetString("EditarCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Canal.
        /// </summary>
        public static string EditarCanal {
            get {
                return ResourceManager.GetString("EditarCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cargo.
        /// </summary>
        public static string EditarCargo {
            get {
                return ResourceManager.GetString("EditarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Categoría.
        /// </summary>
        public static string EditarCategoria {
            get {
                return ResourceManager.GetString("EditarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cliente.
        /// </summary>
        public static string EditarCliente {
            get {
                return ResourceManager.GetString("EditarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Etapa.
        /// </summary>
        public static string EditarEtapa {
            get {
                return ResourceManager.GetString("EditarEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Grupo.
        /// </summary>
        public static string EditarGrupo {
            get {
                return ResourceManager.GetString("EditarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Lote.
        /// </summary>
        public static string EditarLote {
            get {
                return ResourceManager.GetString("EditarLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Memo.
        /// </summary>
        public static string EditarMemo {
            get {
                return ResourceManager.GetString("EditarMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Parámetros.
        /// </summary>
        public static string EditarParametros {
            get {
                return ResourceManager.GetString("EditarParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Programación.
        /// </summary>
        public static string EditarProgramacionRuta {
            get {
                return ResourceManager.GetString("EditarProgramacionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Programación.
        /// </summary>
        public static string EditarProgramacionTarea {
            get {
                return ResourceManager.GetString("EditarProgramacionTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Región.
        /// </summary>
        public static string EditarRegion {
            get {
                return ResourceManager.GetString("EditarRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Reunión.
        /// </summary>
        public static string EditarReunion {
            get {
                return ResourceManager.GetString("EditarReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Ruta.
        /// </summary>
        public static string EditarRuta {
            get {
                return ResourceManager.GetString("EditarRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Subcategoría.
        /// </summary>
        public static string EditarSubcategoria {
            get {
                return ResourceManager.GetString("EditarSubcategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Supervisor.
        /// </summary>
        public static string EditarSupervisor {
            get {
                return ResourceManager.GetString("EditarSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tarea.
        /// </summary>
        public static string EditarTarea {
            get {
                return ResourceManager.GetString("EditarTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tipo de Actividad.
        /// </summary>
        public static string EditarTipoActividad {
            get {
                return ResourceManager.GetString("EditarTipoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tipo de Cartera.
        /// </summary>
        public static string EditarTipoCartera {
            get {
                return ResourceManager.GetString("EditarTipoCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tipo de Cliente.
        /// </summary>
        public static string EditarTipoCliente {
            get {
                return ResourceManager.GetString("EditarTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Zona.
        /// </summary>
        public static string EditarZona {
            get {
                return ResourceManager.GetString("EditarZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Agente.
        /// </summary>
        public static string EliminarAgente {
            get {
                return ResourceManager.GetString("EliminarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Calendario.
        /// </summary>
        public static string EliminarCalendario {
            get {
                return ResourceManager.GetString("EliminarCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Canal.
        /// </summary>
        public static string EliminarCanal {
            get {
                return ResourceManager.GetString("EliminarCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Cargo.
        /// </summary>
        public static string EliminarCargo {
            get {
                return ResourceManager.GetString("EliminarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Cliente.
        /// </summary>
        public static string EliminarCliente {
            get {
                return ResourceManager.GetString("EliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Etapa.
        /// </summary>
        public static string EliminarEtapa {
            get {
                return ResourceManager.GetString("EliminarEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Grupo.
        /// </summary>
        public static string EliminarGrupo {
            get {
                return ResourceManager.GetString("EliminarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Lote.
        /// </summary>
        public static string EliminarLote {
            get {
                return ResourceManager.GetString("EliminarLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Memo.
        /// </summary>
        public static string EliminarMemo {
            get {
                return ResourceManager.GetString("EliminarMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Programación.
        /// </summary>
        public static string EliminarProgramacionRuta {
            get {
                return ResourceManager.GetString("EliminarProgramacionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Programación.
        /// </summary>
        public static string EliminarProgramacionTarea {
            get {
                return ResourceManager.GetString("EliminarProgramacionTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Región.
        /// </summary>
        public static string EliminarRegion {
            get {
                return ResourceManager.GetString("EliminarRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Reunión.
        /// </summary>
        public static string EliminarReunion {
            get {
                return ResourceManager.GetString("EliminarReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Ruta.
        /// </summary>
        public static string EliminarRuta {
            get {
                return ResourceManager.GetString("EliminarRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Subcategoría.
        /// </summary>
        public static string EliminarSubcategoria {
            get {
                return ResourceManager.GetString("EliminarSubcategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Supervisor.
        /// </summary>
        public static string EliminarSupervisor {
            get {
                return ResourceManager.GetString("EliminarSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Tarea.
        /// </summary>
        public static string EliminarTarea {
            get {
                return ResourceManager.GetString("EliminarTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Tipo de Actividad.
        /// </summary>
        public static string EliminarTipoActividad {
            get {
                return ResourceManager.GetString("EliminarTipoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Tipo de Cartera.
        /// </summary>
        public static string EliminarTipoCartera {
            get {
                return ResourceManager.GetString("EliminarTipoCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Tipo de Cliente.
        /// </summary>
        public static string EliminarTipoCliente {
            get {
                return ResourceManager.GetString("EliminarTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Zona.
        /// </summary>
        public static string EliminarZona {
            get {
                return ResourceManager.GetString("EliminarZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio de Notificaciones.
        /// </summary>
        public static string EnvioNotificacion {
            get {
                return ResourceManager.GetString("EnvioNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadística de Encuestas.
        /// </summary>
        public static string EstadisticaEncuesta {
            get {
                return ResourceManager.GetString("EstadisticaEncuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadísticas.
        /// </summary>
        public static string Estadisticas {
            get {
                return ResourceManager.GetString("Estadisticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas.
        /// </summary>
        public static string Etapas {
            get {
                return ResourceManager.GetString("Etapas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapas y Sub-Etapas.
        /// </summary>
        public static string EtapaSubEtapa {
            get {
                return ResourceManager.GetString("EtapaSubEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes a excluir.
        /// </summary>
        public static string ExcluirClientes {
            get {
                return ResourceManager.GetString("ExcluirClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existentes.
        /// </summary>
        public static string Existentes {
            get {
                return ResourceManager.GetString("Existentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocercas.
        /// </summary>
        public static string Geocercas {
            get {
                return ResourceManager.GetString("Geocercas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Gestión Detallado.
        /// </summary>
        public static string GestionDetallado {
            get {
                return ResourceManager.GetString("GestionDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Gestión Resumido.
        /// </summary>
        public static string GestionResumido {
            get {
                return ResourceManager.GetString("GestionResumido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión en Visita.
        /// </summary>
        public static string GestionVisita {
            get {
                return ResourceManager.GetString("GestionVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos.
        /// </summary>
        public static string Grupos {
            get {
                return ResourceManager.GetString("Grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Inicial.
        /// </summary>
        public static string HomeDashboard {
            get {
                return ResourceManager.GetString("HomeDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes a incluir.
        /// </summary>
        public static string IncluirClientes {
            get {
                return ResourceManager.GetString("IncluirClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Trazabilidad.
        /// </summary>
        public static string InformeParada {
            get {
                return ResourceManager.GetString("InformeParada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificaciones.
        /// </summary>
        public static string Justificaciones {
            get {
                return ResourceManager.GetString("Justificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote.
        /// </summary>
        public static string Lote {
            get {
                return ResourceManager.GetString("Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotes y Rutas.
        /// </summary>
        public static string LoteRuta {
            get {
                return ResourceManager.GetString("LoteRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotes.
        /// </summary>
        public static string Lotes {
            get {
                return ResourceManager.GetString("Lotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        public static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memos.
        /// </summary>
        public static string Memos {
            get {
                return ResourceManager.GetString("Memos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevos.
        /// </summary>
        public static string Nuevos {
            get {
                return ResourceManager.GetString("Nuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidades.
        /// </summary>
        public static string Oportunidades {
            get {
                return ResourceManager.GetString("Oportunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenamiento.
        /// </summary>
        public static string Ordenamiento {
            get {
                return ResourceManager.GetString("Ordenamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros Generales.
        /// </summary>
        public static string ParametrosGenerales {
            get {
                return ResourceManager.GetString("ParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicaciones.
        /// </summary>
        public static string ParametrosUbicacion {
            get {
                return ResourceManager.GetString("ParametrosUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido.
        /// </summary>
        public static string Pedido {
            get {
                return ResourceManager.GetString("Pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        public static string Pedidos {
            get {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos Previos.
        /// </summary>
        public static string PermisosPrevios {
            get {
                return ResourceManager.GetString("PermisosPrevios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesar Agenda.
        /// </summary>
        public static string ProcesarAgenda {
            get {
                return ResourceManager.GetString("ProcesarAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesar Lote.
        /// </summary>
        public static string ProcesarLote {
            get {
                return ResourceManager.GetString("ProcesarLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesar Ruta.
        /// </summary>
        public static string ProcesarRuta {
            get {
                return ResourceManager.GetString("ProcesarRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación.
        /// </summary>
        public static string Programacion {
            get {
                return ResourceManager.GetString("Programacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación de Ruta.
        /// </summary>
        public static string ProgramacionRuta {
            get {
                return ResourceManager.GetString("ProgramacionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación de Rutas.
        /// </summary>
        public static string ProgramacionRutas {
            get {
                return ResourceManager.GetString("ProgramacionRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación de Tarea.
        /// </summary>
        public static string ProgramacionTarea {
            get {
                return ResourceManager.GetString("ProgramacionTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación de Tareas.
        /// </summary>
        public static string ProgramacionTareas {
            get {
                return ResourceManager.GetString("ProgramacionTareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasignación de Clientes.
        /// </summary>
        public static string ReasignacionClientes {
            get {
                return ResourceManager.GetString("ReasignacionClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasignar Ruta.
        /// </summary>
        public static string ReasignarRuta {
            get {
                return ResourceManager.GetString("ReasignarRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorrido de Agentes.
        /// </summary>
        public static string RecorridoAgente {
            get {
                return ResourceManager.GetString("RecorridoAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Región.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regiones.
        /// </summary>
        public static string Regiones {
            get {
                return ResourceManager.GetString("Regiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Marcaciones.
        /// </summary>
        public static string ReporteMarcacion {
            get {
                return ResourceManager.GetString("ReporteMarcacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsables.
        /// </summary>
        public static string Responsables {
            get {
                return ResourceManager.GetString("Responsables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen de Gestión.
        /// </summary>
        public static string ResumenGestionChart {
            get {
                return ResourceManager.GetString("ResumenGestionChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunión.
        /// </summary>
        public static string Reunion {
            get {
                return ResourceManager.GetString("Reunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuniones.
        /// </summary>
        public static string Reuniones {
            get {
                return ResourceManager.GetString("Reuniones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        public static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutas.
        /// </summary>
        public static string Rutas {
            get {
                return ResourceManager.GetString("Rutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de Agente.
        /// </summary>
        public static string SeleccionAgente {
            get {
                return ResourceManager.GetString("SeleccionAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de Rol.
        /// </summary>
        public static string SeleccionRol {
            get {
                return ResourceManager.GetString("SeleccionRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoría.
        /// </summary>
        public static string SubCategoria {
            get {
                return ResourceManager.GetString("SubCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategorías.
        /// </summary>
        public static string SubCategorias {
            get {
                return ResourceManager.GetString("SubCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubEtapas.
        /// </summary>
        public static string SubEtapas {
            get {
                return ResourceManager.GetString("SubEtapas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisores.
        /// </summary>
        public static string Supervisores {
            get {
                return ResourceManager.GetString("Supervisores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string Tarea {
            get {
                return ResourceManager.GetString("Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareas.
        /// </summary>
        public static string Tareas {
            get {
                return ResourceManager.GetString("Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Actividad.
        /// </summary>
        public static string TipoActividad {
            get {
                return ResourceManager.GetString("TipoActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Actividad.
        /// </summary>
        public static string TipoActividades {
            get {
                return ResourceManager.GetString("TipoActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cartera.
        /// </summary>
        public static string TipoCartera {
            get {
                return ResourceManager.GetString("TipoCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Cartera.
        /// </summary>
        public static string TipoCarteras {
            get {
                return ResourceManager.GetString("TipoCarteras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cliente.
        /// </summary>
        public static string TipoCliente {
            get {
                return ResourceManager.GetString("TipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Clientes.
        /// </summary>
        public static string TipoClientes {
            get {
                return ResourceManager.GetString("TipoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicaciones de Agentes.
        /// </summary>
        public static string UbicacionAgente {
            get {
                return ResourceManager.GetString("UbicacionAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicaciones.
        /// </summary>
        public static string Ubicaciones {
            get {
                return ResourceManager.GetString("Ubicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string ValorTotal {
            get {
                return ResourceManager.GetString("ValorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitas.
        /// </summary>
        public static string Visitas {
            get {
                return ResourceManager.GetString("Visitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista Previa.
        /// </summary>
        public static string VistaPrevia {
            get {
                return ResourceManager.GetString("VistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de Referencia para Punto de Partida.
        /// </summary>
        public static string ZonaPuntoPartida {
            get {
                return ResourceManager.GetString("ZonaPuntoPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonas.
        /// </summary>
        public static string Zonas {
            get {
                return ResourceManager.GetString("Zonas", resourceCulture);
            }
        }
    }
}
